---
output: github_document
title: "Rtools"
author: "Michael Jahn, "
date: "`r Sys.Date()`"
#output: rmarkdown::html_vignette
#vignette: >
#  %\VignetteIndexEntry{}
#  %\VignetteEngine{knitr::rmarkdown}
#  %\VignetteEncoding{UTF-8}
#
# alternative to create README.md from R markdown source:
# knitr::knit("README.Rmd", "README.md")
---

***

Utility and wrapper functions for bioinformatics work

## Description

This package contains utility and wrapper functions that I often use. It is not intended to be usable by the general public but is maintained as a package for accessability.

## Installation

To install the package directly from github, use this function from devtools package in your R session:

```
require(devtools)
devtools::install_github("https://github.com/m-jahn/R-tools")
```

## Utility functions


### aggregate_pep

Aggregate peptide abundances to protein abundances

### apply_norm

Apply normalization based on different published methods

### baranyi_fun

Baranyi growth model

### custom.ggplot

Custom ggplot2 like theme

### custom.lattice

Custom grey lattice theme

### GetTopGO

Convenience wrapper to TopGO package (Rahnenfueher et al.)

### gompertzm_fun

Modified Gompertz growth model

### mutate_cond

Conditional mutate(), mutating only selected observations (rows)

### OD_corr

Optical density conversion of plate reader to photometer measurements (OD 600 nm)

### panel.barplot

Draw barplot with error bars in lattice plots

### panel.errbars

Calculate and draw error bars in lattice plots

### panel.key

Draw custom keys in lattice plots

### panel.pvalue

Calculate and draw p-values in lattice plots

### panel.quadrants

Draw quadrants and quadrant statistics in lattice plots

### parse_kegg_brite

Parse Kegg Brite xml files step-by-step

### silhouetteAnalysis

Wrapper function to perform silhouette analysis on all clusters of a
